image: maven:3-jdk-8

stages:
  - build
  - test
  - package

build-job:
  stage: build
  script: "mvn -B compile"

test-job:
  stage: test
  script: "mvn -B test"

package:
  stage: package
  script: "mvn -B package"