####
#
# This is a sample configuration. Copy this and place next to the application jar file to override.
#
####
server:
  port: 8443
  ssl:
    key-store: /home/ghaesen/projects/TCBL/test_project/OpenIDConnectTest/cert/keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    key-alias: tomcat

logging:
  level:
    root: debug
    org.springframework.web: debug
    org.springframework.security: debug

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      # config for client on honegger
      tcbl-manager:
        client-id: "@!4F1B.EBA3.75E2.F47A!0001!EF35.6902!0008!1B4C.7A50.7F55.50D7"
        client-secret: averysecrativesecret
        client-authentication-method: post
        authorized-grant-type: authorization_code
        redirect-uri: "https://ravel.elis.ugent.be:8443/oauth2/authorize/code/tcbl_manager"
        scopes: openid, minimum
        authorization-uri: "https://honegger.elis.ugent.be/oxauth/seam/resource/restv1/oxauth/authorize"
        token-uri: "https://honegger.elis.ugent.be/oxauth/seam/resource/restv1/oxauth/token"
        user-info-uri: "https://honegger.elis.ugent.be/oxauth/seam/resource/restv1/oxauth/userinfo"
        user-info-converter: "org.springframework.security.oauth2.client.user.converter.UserInfoConverter"
        client-name: TCBL_manager
        client-alias: tcbl-manager
  scim:
    domain: "https://honegger.elis.ugent.be/identity/seam/resource/restv1"
    meta-data-url: "https://honegger.elis.ugent.be/.well-known/uma-configuration"
    aat-client-id: "@!4F1B.EBA3.75E2.F47A!0001!EF35.6902!0008!224B.6C55"
    aat-client-jks-path: "/home/ghaesen/projects/TCBL/config/scim-rp-honegger.jks"
    aat-client-jks-password: secret
    aat-client-key-id: